spring:
  application:
    name: jzcccProviderByNacos
dubbo:
  scan:
    base-packages: com.jzcccc.dubbo.provider.service
  protocol:
    name: dubbo
    port: 20881
  registry:
#    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
    parameters:
      - register-mode: instance
    use-as-metadata-center: false #不使用配置中心元数据中心，需要在DubboReference 使用providedBy 指定应用
  #    metadata-report:
#    address: zookeeper://127.0.0.1:2181
  #    address: nacos://${nacos.server-address}:${nacos.port}/?username=${nacos.username}&password=${nacos.password}
  application:
    name: jzcccProviderByNacos

nacos:
  server-address: 127.0.0.1
  port: 8848
  username: nacos
  password: nacos
