spring:
  application:
    name: jzcccConsumer
dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
  application:
    service-discovery:
      migration: FORCE_APPLICATION # 只消费应用级地址，如无地址则报错，单订阅 3.x 地址
    name: jzcccConsumer
#    registry: zookeeper://127.0.0.1:2181
